<?php
header("refresh: 30;");
?>


<table>
</table>

TRAFFIC_TOD = ?,AVGBASKET_TOD = ?,WASTE_SUM_TOD = ?,WASTE_ITEMS_TOD = ?,RETURN_NBITEM_TOD = ?,
	RETURN_SUMITEM_TOD = ?,RETURN_AMOUNT_TOD = ?,TRF_ALL_TOD = ?,TRF_RAT_TOD = ?,TRF_OX_TOD = ?,
	TRF_TIGER_TOD = ?,TRF_HARE_TOD = ?,TRF_DRAGON_TOD = ?,TRF_SNAKE_TOD = ?,TRF_HORSE_TOD = ?,
	TRF_GOAT_TOD = ?,OCC_ALL_TOD = ?,OCC_RAT_TOD = ?,OCC_OX_TOD = ?,OCC_TIGER_TOD = ?,
	OCC_HARE_TOD = ?,OCC_DRAGON_TOD = ?,OCC_SNAKE_TOD = ?,OCC_HORSE_TOD = ?,OCC_GOAT_TOD = ?,
	SALE_RAT_TOD = ?,SALE_OX_TOD = ?,SALE_TIGER_TOD = ?,SALE_HARE_TOD = ?,SALE_DRAGON_TOD = ?,
	SALE_SNAKE_TOD = ?,SALE_HORSE_TOD = ?,SALE_GOAT_TOD = ?,EXPIRE_RET_ITEMS = ?,EXPIRE_RET_CNT = ?,
	EXPIRE_NR_ITEMS = ?,EXPIRE_NR_CNT = ?,NEEDMOVE_ITEMS = ?,NEEDMOVE_CNT = ?,NOLOC_ITEMS = ?,
	NOLOC_ITEMS_CNT = ?,NEGATIVEITEM_WH1_ITEMS = ?,NEGATIVEITEM_WH1_CNT = ?,NEGATIVEITEM_WH2_ITEMS = ?,NEGATIVEITEM_WH2_CNT = ?,
	UNSOLD30_ITEMS = ?,PORECEIVED_TOD = ?,NBITEMRECEIVED_TOD = ?,ITEMQTYRECEIVED_TOD = ?,POCREATED_TOD = ?,
	NBITEMORDERED_TOD = ?,QTYITEMORDERED_TOD = ?,ANOMALIES_CNT_NOW = ?,ANOMALIES_ITEMS_NOW = ?,PRICEDIFFERENCES_ITEMS_TOD = ?



    TRAFFIC_YES = ?,AVGBASKET_YES = ?, WASTE_NBITEMS_YES = ?, WASTE_SUM_YES = ?,WASTE_ITEMS_YES = ?,
	RETURN_NBITEM_YES = ?,RETURN_SUMITEM_YES = ?,RETURN_AMOUNT_YES = ?,TRF_ALL_YES = ?,TRF_RAT_YES = ?,
	TRF_OX_YES = ?,TRF_TIGER_YES = ?,TRF_HARE_YES = ?,TRF_DRAGON_YES = ?,TRF_SNAKE_YES = ?,
	TRF_HORSE_YES = ?,TRF_GOAT_YES = ?,OCC_ALL_YES = ?,OCC_RAT_YES = ?,OCC_OX_YES = ?,
	OCC_TIGER_YES = ?,OCC_HARE_YES = ?,OCC_DRAGON_YES = ?,OCC_SNAKE_YES = ?,OCC_HORSE_YES = ?,
	OCC_GOAT_YES = ?,SALE_RAT_YES = ?,SALE_OX_YES = ?,SALE_TIGER_YES = ?,SALE_HARE_YES = ?,
	SALE_DRAGON_YES = ?,SALE_SNAKE_YES = ?,SALE_HORSE_YES = ?,SALE_GOAT_YES = ?,PORECEIVED_YES = ?,
	NBITEMRECEIVED_YES = ?,ITEMQTYRECEIVED_YES = ?,POCREATED_YES = ?,NBITEMORDERED_YES = ?,QTYITEMORDERED_YES = ?,
	PRICEDIFFERENCES_ITEMS_YES = ? WHERE DAY = ?